name: Carl East
favicon: null
layout_spectrum: 0.4420923562720418
typography_spectrum: 0.7774039930664003
title: Carl East -  Erotic Books
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101010'
    - '#444643'
    - '#282826'
    - '#70665c'
    - '#c0b9af'
  brandStrength: 0.4547800989821553
  lightness: 0.7701566214673221
  saturation: 0.7781905438750982
  rhythmicContrast: 0.8510601962916553
purpose: []
